import type { ToolCard } from '../lib/types';

/**
 * Bibliothèque d'outils de la formation, organisée en six familles.
 * Ce sont des choix pédagogiques adaptables, pas six outils imposés :
 * chaque famille propose un à trois outils et une carte de secours
 * (is_fallback) utilisable sans compte ni connexion.
 *
 * Aucun prix, modèle ou lieu d'hébergement n'est présenté ici comme
 * immuable. Seules quatre cartes portent une date de vérification ;
 * les autres sont affichées « à vérifier » par l'application.
 */

export type ToolCardSeed = Omit<ToolCard, 'id' | 'version' | 'updated_at'>;

const PRECAUTIONS_COMMUNES = `Données fictives uniquement (cas Agence Horizon) : ne pas coller de données réelles, ni de noms, ni de coordonnées de personnes accompagnées ou de clients. Pas de partage de comptes entre participants. Respecter les quotas et les conditions d'utilisation. Aucun des éléments de cette carte (conditions, politique de confidentialité, lieu d'hébergement annoncé) ne prouve à lui seul une conformité RGPD : la validation revient à la structure et à son délégué à la protection des données.`;

export const TOOL_CARDS: ToolCardSeed[] = [
  // ===========================================================================
  // Famille 1 — Transcription
  // ===========================================================================
  {
    family: 'transcription',
    name: 'Microsoft Teams (transcription)',
    official_url: 'https://www.microsoft.com/microsoft-teams/',
    usage: `Transcrire une réunion ou un entretien tenu en visioconférence, puis relire la transcription pour en faire un compte rendu.`,
    quick_start: `Rejoignez ou organisez une réunion Teams. Dans la barre de réunion, ouvrez « Plus » puis « Enregistrer et transcrire » et démarrez la transcription, si l'option est proposée. Prévenez les participants que la transcription est active. À la fin, la transcription est disponible dans l'onglet de la réunion ou dans le chat, selon la configuration. Téléchargez-la et relisez chaque passage avant tout usage.`,
    authorization_status: 'to_validate',
    account_required: `Compte professionnel ou scolaire Microsoft 365 avec Teams. La fonction peut être désactivée par l'administrateur.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Inclus ou non selon la licence Microsoft 365 de l'organisation ; à vérifier auprès de l'administrateur.`,
    limits: `La disponibilité de la transcription dépend notamment des politiques de l'organisation, des rôles dans la réunion (organisateur, co-organisateur, invité) et des licences. La langue parlée doit être définie correctement. Les transcriptions contiennent des erreurs de reconnaissance et des confusions de locuteurs.`,
    formats: `Transcription consultable dans Teams ; export en .docx ou .vtt selon la configuration.`,
    precautions: `${PRECAUTIONS_COMMUNES} Informer explicitement toute personne présente qu'une transcription est en cours ; en formation, n'enregistrer que des échanges joués à partir du cas fictif.`,
    terms_url: 'https://www.microsoft.com/licensing/terms',
    privacy_url: 'https://privacy.microsoft.com',
    fallback: `Utiliser la transcription fictive fournie (R1).`,
    last_verified_on: '2026-10-01',
    verification_source:
      'https://support.microsoft.com/en-us/teams/meetings/i-can-t-transcribe-a-meeting-in-microsoft-teams',
    is_fallback: false,
  },
  {
    family: 'transcription',
    name: 'Outil de transcription validé par la structure',
    official_url: '',
    usage: `Carte générique pour l'outil de transcription (dictée, enregistreur, service de transcription) que la structure a autorisé pour ses usages internes.`,
    quick_start: `Demandez au formateur ou au référent quel outil est autorisé et avec quel compte. Testez-le sur une phrase courte lue à voix haute. Vérifiez où le fichier audio et la transcription sont stockés. Relisez la transcription en entier avant de la transmettre à un assistant.`,
    authorization_status: 'to_validate',
    account_required: `Selon l'outil retenu par la structure.`,
    pricing_status: 'unknown',
    pricing_note: `À renseigner par la structure selon l'outil choisi.`,
    limits: `Qualité variable selon le micro, le bruit ambiant et la langue. Les noms propres et les chiffres sont souvent mal transcrits.`,
    formats: `Selon l'outil : texte brut, .docx, .srt ou .vtt.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier avant usage où sont stockés les enregistrements et pendant combien de temps.`,
    terms_url: '',
    privacy_url: '',
    fallback: `Utiliser la transcription fictive fournie (R1).`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'transcription',
    name: 'Transcription fictive fournie (R1)',
    official_url: '',
    usage: `Carte de secours : travailler directement à partir de la transcription fictive R1, sans aucun outil de transcription.`,
    quick_start: `Ouvrez la ressource R1 dans l'application. Lisez le dialogue en entier. Repérez les faits établis, les points à confirmer et les informations manquantes. Rédigez le compte rendu à partir de ce texte, avec ou sans assistant.`,
    authorization_status: 'authorized',
    account_required: `Aucun compte nécessaire.`,
    pricing_status: 'free',
    pricing_note: `Ressource interne de la formation.`,
    limits: `Pas de son ni d'enregistrement : l'exercice porte sur la relecture et la rédaction, pas sur la reconnaissance vocale.`,
    formats: `Texte dans l'application, copiable.`,
    precautions: `${PRECAUTIONS_COMMUNES} Le texte R1 est fictif ; il ne doit pas être enrichi d'éléments réels.`,
    terms_url: '',
    privacy_url: '',
    fallback: `C'est la carte de secours de la famille Transcription.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: true,
  },

  // ===========================================================================
  // Famille 2 — Documents
  // ===========================================================================
  {
    family: 'documents',
    name: 'Gemini Notebook (anciennement NotebookLM)',
    official_url: 'https://workspace.google.com/products/gemini-notebook/',
    usage: `Importer un ensemble de documents (fiches, procédures, guides) et leur poser des questions avec des réponses qui renvoient aux passages sources.`,
    quick_start: `Connectez-vous avec le compte autorisé et créez un carnet. Ajoutez les ressources fictives (R2, R4, R5) en texte ou en fichier. Posez une question précise, par exemple sur les horaires ou les informations manquantes. Ouvrez chaque citation proposée pour vérifier qu'elle dit bien ce que la réponse affirme. Notez la version du document citée.`,
    authorization_status: 'to_validate',
    account_required: `Compte Google. Les conditions diffèrent selon le type de compte (personnel, Workspace, éducation).`,
    pricing_status: 'depends_on_account',
    pricing_note: `Des offres gratuites et payantes existent selon le type de compte et la région ; à revérifier sur le site officiel.`,
    limits: `Nombre de sources et de carnets limité selon l'offre. Les réponses dépendent entièrement des documents importés : si deux versions contradictoires sont importées, la réponse peut mélanger les deux. Les citations sont à contrôler une par une.`,
    formats: `Texte collé, PDF, Google Docs, pages web et autres formats selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES} Les conditions Google diffèrent selon le type de compte (personnel, Workspace, éducation) : vérifier lequel est utilisé avant d'importer un document.`,
    terms_url: 'https://policies.google.com/terms',
    privacy_url: 'https://support.google.com/gemininotebook/answer/17004255?hl=en',
    fallback: `Construire la FAQ à la main à partir des documents, sans outil.`,
    last_verified_on: '2026-10-01',
    verification_source: 'https://support.google.com/gemininotebook/answer/17004255?hl=en',
    is_fallback: false,
  },
  {
    family: 'documents',
    name: 'Assistant avec pièces jointes',
    official_url: '',
    usage: `Carte générique : utiliser un assistant conversationnel autorisé qui accepte des fichiers joints, pour interroger les documents fictifs.`,
    quick_start: `Ouvrez l'assistant autorisé par la structure. Joignez ou collez les documents fictifs utiles. Demandez des réponses qui citent le document et le passage exact. Vérifiez chaque citation dans le document d'origine. Signalez dans votre production les réponses que l'assistant n'a pas pu appuyer sur un passage.`,
    authorization_status: 'to_validate',
    account_required: `Selon l'assistant retenu par la structure.`,
    pricing_status: 'unknown',
    pricing_note: `À renseigner selon l'assistant choisi.`,
    limits: `Taille et nombre de fichiers limités selon l'offre. Les assistants peuvent inventer une citation plausible : seul le document fait foi.`,
    formats: `Texte collé, PDF, .docx selon l'assistant.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier si les fichiers joints sont conservés par le service et pendant combien de temps.`,
    terms_url: '',
    privacy_url: '',
    fallback: `Construire la FAQ à la main à partir des documents, sans outil.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'documents',
    name: 'FAQ texte à partir des documents (sans outil)',
    official_url: '',
    usage: `Carte de secours : rédiger une FAQ sourcée en lisant les documents fictifs et en recopiant les passages exacts.`,
    quick_start: `Listez cinq questions qu'une personne accompagnée pourrait poser. Cherchez la réponse dans R2, R4 et R5. Pour chaque réponse, notez le code du document, sa version et le passage recopié. Si aucun document ne répond, écrivez « information non disponible » et nommez qui doit la demander.`,
    authorization_status: 'authorized',
    account_required: `Aucun compte nécessaire.`,
    pricing_status: 'free',
    pricing_note: `Aucun coût.`,
    limits: `Plus lent qu'un outil ; demande une lecture complète des documents.`,
    formats: `Texte dans le formulaire de production de l'application.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: '',
    privacy_url: '',
    fallback: `C'est la carte de secours de la famille Documents.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: true,
  },

  // ===========================================================================
  // Famille 3 — Recherche
  // ===========================================================================
  {
    family: 'recherche',
    name: `Assistant disposant d'une recherche web`,
    official_url: '',
    usage: `Carte générique : utiliser un assistant autorisé capable de consulter le web, pour préparer une visite d'entreprise à partir de sources institutionnelles.`,
    quick_start: `Partez des points de départ de la ressource R7. Demandez à l'assistant de citer la page précise pour chaque information. Ouvrez chaque page citée et vérifiez le passage exact. Notez la date de publication et la date de consultation. Rejetez toute information que vous ne retrouvez pas sur la page.`,
    authorization_status: 'to_validate',
    account_required: `Selon l'assistant retenu par la structure.`,
    pricing_status: 'unknown',
    pricing_note: `À renseigner selon l'assistant choisi.`,
    limits: `Les résumés peuvent mélanger plusieurs pages ou dater d'une version ancienne. Certaines pages institutionnelles ne sont pas accessibles à l'outil.`,
    formats: `Réponses textuelles avec liens.`,
    precautions: `${PRECAUTIONS_COMMUNES} Ne jamais saisir le nom réel d'un client ou d'une personne dans une requête de recherche pendant la formation.`,
    terms_url: '',
    privacy_url: '',
    fallback: `Utiliser le dossier de pages capturées préparé par le formateur.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'recherche',
    name: 'Perplexity',
    official_url: 'https://www.perplexity.ai',
    usage: `Moteur de réponse qui propose des réponses accompagnées de liens vers les pages consultées.`,
    quick_start: `Ouvrez le site et, si nécessaire, connectez-vous avec le compte autorisé. Saisissez une question précise et, si possible, le nom du site institutionnel visé. Ouvrez chaque lien cité et vérifiez le passage exact. Reportez la page, la date de publication et la date de consultation dans votre fiche de visite.`,
    authorization_status: 'to_validate',
    account_required: `Utilisation possible sans compte avec des limites ; un compte est demandé pour certaines fonctions.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Offre gratuite avec limites et offres payantes ; conditions à revérifier sur le site officiel.`,
    limits: `Les sources citées ne couvrent pas toujours toute la réponse. Les quotas de requêtes avancées varient selon l'offre.`,
    formats: `Réponses textuelles avec liens ; export selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: 'https://www.perplexity.ai/hub/legal/terms-of-service',
    privacy_url: 'https://www.perplexity.ai/hub/legal/privacy-policy',
    fallback: `Utiliser le dossier de pages capturées préparé par le formateur.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'recherche',
    name: 'Dossier de pages capturées préparé par le formateur',
    official_url: '',
    usage: `Carte de secours : travailler sur un dossier de pages institutionnelles enregistrées (PDF ou captures) préparé par le formateur, sans accès web.`,
    quick_start: `Ouvrez le dossier fourni par le formateur. Pour chaque page, relevez l'adresse, la date de publication si elle figure et la date de capture. Cherchez les informations utiles à la visite et recopiez le passage exact. Remplissez le tableau de sources de la ressource R7.`,
    authorization_status: 'authorized',
    account_required: `Aucun compte nécessaire.`,
    pricing_status: 'free',
    pricing_note: `Aucun coût.`,
    limits: `Les pages peuvent être anciennes au moment de la formation : indiquer la date de capture.`,
    formats: `PDF ou images fournis par le formateur.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: '',
    privacy_url: '',
    fallback: `C'est la carte de secours de la famille Recherche.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: true,
  },

  // ===========================================================================
  // Famille 4 — Schémas
  // ===========================================================================
  {
    family: 'schemas',
    name: 'Napkin',
    official_url: 'https://www.napkin.ai',
    usage: `Transformer un texte (par exemple les six étapes de la procédure R4) en schéma visuel modifiable.`,
    quick_start: `Connectez-vous avec le compte autorisé et créez un nouveau document. Collez le texte des six étapes de la procédure fictive. Sélectionnez le passage et demandez une visualisation ; choisissez un style de type parcours ou étapes. Corrigez les libellés pour qu'ils restent fidèles au texte source. Exportez le schéma dans le format autorisé.`,
    authorization_status: 'to_validate',
    account_required: `Compte requis (adresse e-mail ou compte Google).`,
    pricing_status: 'free_with_quota',
    pricing_note: `Offre gratuite avec quotas et marquage ; offres payantes pour lever ces limites. À revérifier sur https://www.napkin.ai/pricing/`,
    limits: `Quotas de génération et marquage sur l'offre gratuite. Les schémas proposés peuvent réordonner ou fusionner des étapes : vérifier la fidélité au texte.`,
    formats: `Export PNG, SVG ou PDF selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: 'https://www.napkin.ai/terms',
    privacy_url: 'https://www.napkin.ai/privacy',
    fallback: `Utiliser les six blocs éditables de l'application (impression PDF).`,
    last_verified_on: '2026-10-01',
    verification_source: 'https://www.napkin.ai/pricing/',
    is_fallback: false,
  },
  {
    family: 'schemas',
    name: 'Outil de diagrammes autorisé par la structure',
    official_url: '',
    usage: `Carte générique : outil de diagrammes déjà disponible dans la structure (suite bureautique, outil de dessin ou de cartes mentales).`,
    quick_start: `Ouvrez l'outil de diagrammes autorisé. Créez six formes reliées par des flèches, une par étape de la procédure R4. Reprenez les libellés exacts des étapes. Ajoutez un titre et la mention du cas fictif. Exportez en PDF ou en image.`,
    authorization_status: 'to_validate',
    account_required: `Selon l'outil retenu par la structure.`,
    pricing_status: 'unknown',
    pricing_note: `À renseigner selon l'outil choisi.`,
    limits: `Pas de génération automatique : la mise en page est manuelle.`,
    formats: `Selon l'outil : PDF, PNG, SVG.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: '',
    privacy_url: '',
    fallback: `Utiliser les six blocs éditables de l'application (impression PDF).`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'schemas',
    name: `Six blocs éditables dans l'application (impression PDF)`,
    official_url: '',
    usage: `Carte de secours : remplir six blocs directement dans le formulaire de production de l'application, puis imprimer en PDF.`,
    quick_start: `Ouvrez l'atelier Schémas dans l'application. Remplissez les six blocs avec le titre et le contenu de chaque étape. Vérifiez l'ordre et la fidélité au texte R4. Utilisez la fonction d'impression du navigateur pour obtenir un PDF.`,
    authorization_status: 'authorized',
    account_required: `Aucun compte supplémentaire : accès participant à l'application.`,
    pricing_status: 'free',
    pricing_note: `Aucun coût.`,
    limits: `Mise en forme simple, sans icônes ni flèches personnalisées.`,
    formats: `PDF via l'impression du navigateur.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: '',
    privacy_url: '',
    fallback: `C'est la carte de secours de la famille Schémas.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: true,
  },

  // ===========================================================================
  // Famille 5 — Images
  // ===========================================================================
  {
    family: 'images',
    name: `Outil de génération d'images autorisé`,
    official_url: '',
    usage: `Carte générique : générer une illustration pour l'affiche « Préparer sa première mission » avec l'outil de génération d'images que la structure a autorisé.`,
    quick_start: `Rédigez une description courte de la scène souhaitée, sans texte dans l'image et sans stéréotype. Générez plusieurs variantes. Vérifiez les mains, les objets, la diversité des personnes et l'absence de logo ou de marque réelle. Conservez la variante la plus sobre et notez l'outil utilisé.`,
    authorization_status: 'to_validate',
    account_required: `Selon l'outil retenu par la structure.`,
    pricing_status: 'unknown',
    pricing_note: `À renseigner selon l'outil choisi ; les quotas de génération varient fortement.`,
    limits: `Le texte intégré aux images est souvent incorrect. Les droits d'usage des images générées dépendent des conditions de l'outil.`,
    formats: `PNG ou JPEG selon l'outil.`,
    precautions: `${PRECAUTIONS_COMMUNES} Ne jamais générer l'image d'une personne réelle ; vérifier les conditions d'usage des images produites.`,
    terms_url: '',
    privacy_url: '',
    fallback: `Utiliser des pictogrammes sous licence identifiée et des formes simples.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'images',
    name: 'Éditeur de composition (Canva ou équivalent autorisé)',
    official_url: 'https://www.canva.com',
    usage: `Composer l'affiche (titre, trois actions, signature) à partir de formes, de pictogrammes et éventuellement d'une image générée.`,
    quick_start: `Connectez-vous avec le compte autorisé et créez un format affiche. Placez le titre, les trois actions du brief R6 et la signature « START EVOLUTION ». Utilisez des pictogrammes dont la licence est indiquée. Vérifiez la lisibilité et le contraste. Exportez en PDF ou PNG.`,
    authorization_status: 'to_validate',
    account_required: `Compte requis ; les fonctions disponibles dépendent de l'offre.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Offre gratuite avec limites et offres payantes ; certains éléments de la bibliothèque sont payants. À revérifier sur le site officiel.`,
    limits: `Certains éléments graphiques sont réservés aux offres payantes. Les fonctions d'IA intégrées ont leurs propres quotas et conditions.`,
    formats: `PDF, PNG, JPEG.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier la licence de chaque élément graphique utilisé.`,
    terms_url: 'https://www.canva.com/policies/terms-of-use/',
    privacy_url: 'https://www.canva.com/policies/privacy-policy/',
    fallback: `Utiliser des pictogrammes sous licence identifiée et des formes simples.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'images',
    name: 'Pictogrammes sous licence identifiée et formes simples',
    official_url: '',
    usage: `Carte de secours : composer l'affiche avec des pictogrammes dont la licence est connue et des formes simples, dans un outil bureautique ou dans l'application.`,
    quick_start: `Choisissez trois pictogrammes (horaires, questions, trajet) dont la licence est indiquée et notez leur source. Placez le titre, les trois actions et la signature textuelle « START EVOLUTION ». Utilisez des formes simples (cadres, flèches) pour structurer l'affiche. Exportez ou imprimez en PDF.`,
    authorization_status: 'authorized',
    account_required: `Aucun compte nécessaire.`,
    pricing_status: 'free',
    pricing_note: `Aucun coût si les pictogrammes sont sous licence libre ou fournis par la structure.`,
    limits: `Rendu plus sobre qu'une image générée ; le choix des pictogrammes demande de vérifier la licence.`,
    formats: `PDF, PNG.`,
    precautions: `${PRECAUTIONS_COMMUNES} Indiquer la source et la licence de chaque pictogramme.`,
    terms_url: '',
    privacy_url: '',
    fallback: `C'est la carte de secours de la famille Images.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: true,
  },

  // ===========================================================================
  // Famille 6 — Assistants
  // ===========================================================================
  {
    family: 'assistants',
    name: 'ChatGPT',
    official_url: 'https://chatgpt.com',
    usage: `Assistant conversationnel généraliste, utilisable pour rédiger, reformuler ou comparer des réponses à partir du cas fictif.`,
    quick_start: `Connectez-vous avec le compte autorisé. Utilisez le constructeur de prompt de l'application pour préparer votre demande (contexte, tâche, données fictives, contraintes, format, contrôles). Collez-la dans l'assistant. Comparez la réponse avec les documents sources et notez les écarts.`,
    authorization_status: 'to_validate',
    account_required: `Compte requis pour la plupart des usages ; les offres et fonctions varient selon le compte.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Offre gratuite avec limites et offres payantes ; conditions à revérifier sur le site officiel.`,
    limits: `Quotas de messages et accès aux fonctions avancées selon l'offre. L'assistant peut produire des informations plausibles mais fausses.`,
    formats: `Texte, fichiers joints et images selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier les réglages de conservation et d'utilisation des conversations.`,
    terms_url: 'https://openai.com/policies/terms-of-use/',
    privacy_url: 'https://openai.com/policies/privacy-policy/',
    fallback: `Utiliser la comparaison de deux réponses d'exemple fournie par le formateur.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'assistants',
    name: 'Claude',
    official_url: 'https://claude.ai',
    usage: `Assistant conversationnel généraliste, utilisable pour rédiger, structurer ou comparer des réponses à partir du cas fictif.`,
    quick_start: `Connectez-vous avec le compte autorisé. Préparez votre demande avec le constructeur de prompt de l'application. Collez-la dans l'assistant et demandez une réponse qui distingue faits établis, points à confirmer et informations manquantes. Relisez la réponse face aux documents sources.`,
    authorization_status: 'to_validate',
    account_required: `Compte requis ; les offres et fonctions varient selon le compte.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Offre gratuite avec limites et offres payantes ; conditions à revérifier sur le site officiel.`,
    limits: `Quotas d'usage selon l'offre. L'assistant peut inventer des détails s'ils manquent dans les documents fournis.`,
    formats: `Texte, fichiers joints et images selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier les réglages de conservation et d'utilisation des conversations.`,
    terms_url: 'https://www.anthropic.com/legal/consumer-terms',
    privacy_url: 'https://www.anthropic.com/legal/privacy',
    fallback: `Utiliser la comparaison de deux réponses d'exemple fournie par le formateur.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'assistants',
    name: 'Gemini',
    official_url: 'https://gemini.google.com',
    usage: `Assistant conversationnel généraliste de Google, utilisable pour rédiger ou comparer des réponses à partir du cas fictif.`,
    quick_start: `Connectez-vous avec le compte Google autorisé. Préparez votre demande avec le constructeur de prompt de l'application. Collez-la dans l'assistant et demandez des réponses qui signalent les informations manquantes. Relisez la réponse face aux documents sources.`,
    authorization_status: 'to_validate',
    account_required: `Compte Google requis ; les conditions diffèrent selon le type de compte (personnel, Workspace, éducation).`,
    pricing_status: 'depends_on_account',
    pricing_note: `Offre gratuite avec limites et offres payantes ; conditions à revérifier sur le site officiel.`,
    limits: `Quotas et fonctions selon le type de compte. L'assistant peut produire des informations plausibles mais fausses.`,
    formats: `Texte, fichiers joints et images selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier les réglages d'activité et de conservation du compte Google.`,
    terms_url: 'https://policies.google.com/terms',
    privacy_url: 'https://policies.google.com/privacy',
    fallback: `Utiliser la comparaison de deux réponses d'exemple fournie par le formateur.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'assistants',
    name: 'Le Chat (Mistral)',
    official_url: 'https://chat.mistral.ai',
    usage: `Assistant conversationnel généraliste de Mistral AI, utilisable pour rédiger ou comparer des réponses à partir du cas fictif.`,
    quick_start: `Connectez-vous avec le compte autorisé. Préparez votre demande avec le constructeur de prompt de l'application. Collez-la dans l'assistant et demandez une réponse structurée. Relisez la réponse face aux documents sources et notez les écarts.`,
    authorization_status: 'to_validate',
    account_required: `Compte requis ; les offres et fonctions varient selon le compte.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Offre gratuite avec limites et offres payantes ; conditions à revérifier sur le site officiel.`,
    limits: `Quotas d'usage selon l'offre. L'assistant peut produire des informations plausibles mais fausses.`,
    formats: `Texte et fichiers joints selon l'offre.`,
    precautions: `${PRECAUTIONS_COMMUNES} Vérifier les réglages de conservation et d'utilisation des conversations.`,
    terms_url: 'https://mistral.ai/terms',
    privacy_url: 'https://mistral.ai/terms#privacy-policy',
    fallback: `Utiliser la comparaison de deux réponses d'exemple fournie par le formateur.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: false,
  },
  {
    family: 'assistants',
    name: 'Microsoft Copilot',
    official_url: 'https://copilot.microsoft.com',
    usage: `Assistant conversationnel de Microsoft, utilisable avec un compte personnel ou professionnel pour rédiger ou comparer des réponses à partir du cas fictif.`,
    quick_start: `Connectez-vous avec le compte autorisé par la structure. Vérifiez quel mode est actif (compte personnel ou compte professionnel) car les protections diffèrent. Préparez votre demande avec le constructeur de prompt de l'application et collez-la. Relisez la réponse face aux documents sources.`,
    authorization_status: 'to_validate',
    account_required: `Compte Microsoft personnel, professionnel ou scolaire ; les fonctionnalités dépendent du compte et des licences.`,
    pricing_status: 'depends_on_account',
    pricing_note: `Accès de base avec un compte ; fonctions supplémentaires soumises à une licence Microsoft 365 Copilot. À revérifier auprès de l'administrateur.`,
    limits: `Les fonctionnalités dépendent du compte et des licences : l'accès aux documents de l'organisation, les protections de données et certaines fonctions ne sont disponibles qu'avec une licence Microsoft 365 Copilot.`,
    formats: `Texte, fichiers joints et images selon le compte.`,
    precautions: `${PRECAUTIONS_COMMUNES} Ne pas confondre le mode personnel et le mode professionnel : vérifier l'indication affichée dans l'interface.`,
    terms_url: 'https://www.microsoft.com/licensing/terms',
    privacy_url: 'https://privacy.microsoft.com',
    fallback: `Utiliser la comparaison de deux réponses d'exemple fournie par le formateur.`,
    last_verified_on: '2026-10-01',
    verification_source:
      'https://support.microsoft.com/en-us/microsoft-365-copilot/how-copilot-chat-works-with-and-without-a-microsoft-365-copilot-license',
    is_fallback: false,
  },
  {
    family: 'assistants',
    name: `Comparaison de deux réponses d'exemple`,
    official_url: '',
    usage: `Carte de secours : comparer deux réponses d'assistants fournies par le formateur, sans accès à un assistant.`,
    quick_start: `Ouvrez les deux réponses d'exemple fournies par le formateur pour le même prompt. Repérez pour chacune les faits exacts, les erreurs et les informations inventées par rapport aux documents sources. Remplissez la grille de comparaison de l'application. Concluez sur l'assistant le plus adapté à cette tâche et à ces contraintes, sans classement général.`,
    authorization_status: 'authorized',
    account_required: `Aucun compte nécessaire.`,
    pricing_status: 'free',
    pricing_note: `Aucun coût.`,
    limits: `Les réponses sont figées ; l'exercice porte sur l'analyse, pas sur la manipulation d'un outil.`,
    formats: `Texte fourni par le formateur.`,
    precautions: `${PRECAUTIONS_COMMUNES}`,
    terms_url: '',
    privacy_url: '',
    fallback: `C'est la carte de secours de la famille Assistants.`,
    last_verified_on: null,
    verification_source: '',
    is_fallback: true,
  },
];
